How to create the datafram

In [5]:
import numpy as np
import pandas as pd

In [6]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
new = pd.DataFrame(data)

In [3]:
new

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [8]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
new_list = pd.DataFrame(data_list)
new_list
column = ["Name","Age","City","Salary"]
new_list = pd.DataFrame(data_list,columns = column)
new_list

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [9]:
new_list

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

SELECTION AND INDEXING OF COLUMN

In [12]:
new_list['Name']
new_list[['Name','Age']]

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

CREATING NEW COLUMN IN TABLE

In [14]:
new_list['designation'] = ['doc','engg','doc','engg']
new_list

    Name  Age      City  Salary designation
0   John   28  New York   65000         doc
1   Anna   34     Paris   70000        engg
2  Peter   29    Berlin   62000         doc
3  Linda   42    London   85000        engg

DELETING THE COLUMN

In [1]:
new_list.drop('designation',axis=1,inplace=True)

NameError: name 'new_list' is not defined

In [18]:
new_list

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [19]:
new_list.drop(0,axis = 0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [23]:
new_list.loc[1]

Name       Anna
Age          34
City      Paris
Salary    70000
Name: 1, dtype: object

In [3]:
new_list.iloc[[2,3]]

NameError: name 'new_list' is not defined

Selecting subset of rows and column

In [1]:
new_list

NameError: name 'new_list' is not defined

In [9]:
new_list

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [15]:
new_list.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [16]:
new_list.loc[[2,3],["Name","Salary"]]

    Name  Salary
2  Peter   62000
3  Linda   85000

Condition Selection

condition Selection

In [17]:
new_list

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [21]:
new_list[new_list["Age"] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [23]:
#and also want who's city is londan
new_list[(new_list["Age"] > 30) & (new_list["City"]=='London')]

    Name  Age    City  Salary
3  Linda   42  London   85000