In [2]:
import numpy as np
import pandas as pd
from pandas.conftest import axis

In [2]:
list = [1,2,3,4]
index = ['a','b','c','d']
arr = np.array([1,2,3,4])
dic = {'a':1,'b':2,'c':3}

In [3]:
arr

array([1, 2, 3, 4])

In [5]:
pd.Series(arr,index=index)

a    1
b    2
c    3
d    4
dtype: int64

In [3]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
d1=pd.DataFrame(data)

In [4]:
d1

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [9]:
d1[['Age','City']]

   Age      City
0   28  New York
1   34     Paris
2   29    Berlin
3   42    London

In [10]:
d1['designation'] = ['Enggering','Doctor','Engineering','doctor'] # adding the new column and data to row
d1

    Name  Age      City  Salary  designation
0   John   28  New York   65000    Enggering
1   Anna   34     Paris   70000       Doctor
2  Peter   29    Berlin   62000  Engineering
3  Linda   42    London   85000       doctor

In [12]:
d1[['Age','City']]

   Age      City
0   28  New York
1   34     Paris
2   29    Berlin
3   42    London

In [19]:
d1.loc[[0,1]][['Age','Name']]

   Age  Name
0   28  John
1   34  Anna

In [22]:
d1[(d1['Age'] > 30)&(d1['City'] == 'Paris')]

   Name  Age   City  Salary designation
1  Anna   34  Paris   70000      Doctor

In [25]:
d1.drop['designation' ,axis = 0 , inplace=True]

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (1625041504.py, line 1)